name: Deploy to GCP
on:
  workflow_dispatch:
permissions:
  id-token: write  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0.5.0
      with:
        token_format: access_token
        workload_identity_provider: projects/1077328746160/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: 1077328746160-compute@developer.gserviceaccount.com 

    - name: Deploy to GCP
      run: |
        # Use gcloud commands to interact with GCP resources
        gcloud auth use-access-token
        gcloud containers clusters list
