jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0.5.0
      with:
        token_format: access_token
        workload_identity_provider: projects/75528258152/locations/global/workloadIdentityPools/my-pool/providers/my-github-provider
        service_account: basic-user@playground-s-11-fbae91bc.iam.gserviceaccount.com 

    - name: Deploy to GCP
      run: |
        # Use gcloud commands to interact with GCP resources
        gcloud auth use-access-token
        gcloud containers clusters list
